### ISSUE TITLE
How does memoization work?

### ISSUE THREAD

**Issue by egeriis** [HeyImAlex/reselect-map#3]
Hi there,

This looks very interesting for a use case that we have. But I have a question regarding memoization, because we're having an issue with the regular selectors from reselect.

Take this data set (it's a [JSON API](http://jsonapi.org) collection):

```json
[
  { "type": "tasks", "id": "1", "attributes": { "name": "Do stuff" } },
  { "type": "tasks", "id": "2", "attributes": { "name": "Procrastinate" } }
]
```

We could create a selector with reselect, that would accept a function returning this array as the first argument and find a particular object in the callback:

```js
const resourceSelector = createSelector(
  state => state.resourceCollection,
  resourceCollection => resourceCollection.find(res => res.id === '1')
);
```

The problem we have with this solution is that the memoization will not be optimized for our use case, as we would like for the selector to only run if the output actually changes. 
Quick note: we build our own equalityCheck to check prev/next attributes for these particular objects.

I understand that this is due to the memoization looking at the _input_ to the selectors, i.e. the collection of resources. So if another resource was added, it would not return the cached value and our component would re-render.

Would I be correct in assuming that this could be one of the use cases for reselect-map?

Our current workaround is simply to do this:

```js
const giveMeResource = createSelector(
  resourceSelector,
  resource => resource
);
```

That's stupid 😞

**Comment by HeyImAlex** [comment]
I don't really understand, maybe you could provide a more descriptive example and I could be of more help? In any case, I don't _think_ reselect map would be a good fit because I don't see any mapping.

Also, I don't understand why you need the `giveMeResource` function? Even if `resourceSelector` runs every time, the _result_ will always be the same (unless the resource with `id === 1` actually changes) so any sub-selectors/components won't update.

**Comment by egeriis** [comment]
Thank you for the swift response, @HeyImAlex.

The thing is, that we've build this library that helps us manage JSON API resources in Redux state. When it's reading from an endpoint, it will replace a resource if the API responds with a resource of same type and ID. We do this to avoid having to do a deep equal, as this felt more performant. 
Maybe we're wrong.

We then managed to get the functionality we were looking for, by making our own selector creator, which uses another equality logic than the default strict equal check. But it feels dirty, and then I stumbled upon _reselect-map_.

**Comment by LiborOl** [comment]
Hi egeriis.

I think I understand your problem and what are you trying to do. 
The solution can be: When you got new response from the endpoint, create a new array to the Redux store and put there all items from the array of the old store which are present in the new response. Then append/insert the new items from the response to this array. (In another words, don't replace items, that are already in the store but use them).
Then your resourceSelector will alway return the same instance of the object, because the instance of item id==1 will be the same in the store.
This solution is possible only, if you the attributes of the new instances of items do not change and you are not using this changes on another place in your application.

@HeyImAlex - giveMeResource result will not be the same because of custom equality check that checks only some attributes. It can use value from cache event if the instances are different.

**Comment by egeriis** [comment]
@HeyImAlex Yes, I have been thinking about placing this in the library we use for API state management. However I thought about it having too hard a hit on performance (not proven, nor tested). But you have a point.

Thank you for the tip regarding custom memoize function, that's probably what we're looking for right now, yes :) 

I appreciate the help, @HeyImAlex + @LiborOl
